#!/bin/bash

export BROWSER=firefox
export EDITOR=nvim
export VISUAL=nvim

# SSH Agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# GO
export GOPATH=$HOME/.local/share/go

# PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/go/bin:$PATH

# HISTORY
HISTFILE=$HOME/.local/share/zsh/history
HISTSIZE=5000
SAVEHIST=5000

